# Generated by Django 4.1 on 2022-08-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='Grape', max_length=100),
            preserve_default=False,
        ),
    ]
